eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8088
spring:
  application:
    name: chagpts

openai:
  model: "gpt-3.5-turbo"
  api:
    key: "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"
    url: "https://api.openai.com/v1/chat/completions"